// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2_TaiTungHung.Models;

#nullable disable

namespace Project2_TaiTungHung.Migrations
{
    [DbContext(typeof(CuaHangBanhNgotContext))]
    partial class CuaHangBanhNgotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project2_TaiTungHung.Models.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([SoLuong]*[DonGia])", true);

                    b.HasKey("MaHd", "MaSp")
                        .HasName("PK__ChiTietH__F557F661151B2D0D");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly?>("NgayLap")
                        .HasColumnType("date");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E04D6C558A");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E7B4FB73A");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNcc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc")
                        .HasName("PK__NhaCungC__3A185DEBB26ED3ED");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A04FAC771");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C9E0C6741");

                    b.HasIndex("MaNcc");

                    b.ToTable("SanPham", (string)null);

                    b.HasData(
                        new
                        {
                            MaSp = "1",
                            DonGia = 120000m,
                            MaNcc = "NCC1",
                            SoLuong = 10,
                            TenSp = "Bánh sinh nhật"
                        },
                        new
                        {
                            MaSp = "2",
                            DonGia = 25000m,
                            MaNcc = "NCC1",
                            SoLuong = 20,
                            TenSp = "Bánh tươi"
                        },
                        new
                        {
                            MaSp = "3",
                            DonGia = 18000m,
                            MaNcc = "NCC2",
                            SoLuong = 30,
                            TenSp = "Bánh miếng nhỏ"
                        },
                        new
                        {
                            MaSp = "4",
                            DonGia = 25000m,
                            MaNcc = "NCC2",
                            SoLuong = 15,
                            TenSp = "Bánh cheesecake dâu"
                        },
                        new
                        {
                            MaSp = "5",
                            DonGia = 30000m,
                            MaNcc = "NCC2",
                            SoLuong = 12,
                            TenSp = "Bánh tart trái cây"
                        },
                        new
                        {
                            MaSp = "6",
                            DonGia = 28000m,
                            MaNcc = "NCC3",
                            SoLuong = 25,
                            TenSp = "Bánh croissant"
                        },
                        new
                        {
                            MaSp = "7",
                            DonGia = 35000m,
                            MaNcc = "NCC3",
                            SoLuong = 8,
                            TenSp = "Bánh su kem"
                        },
                        new
                        {
                            MaSp = "8",
                            DonGia = 22000m,
                            MaNcc = "NCC3",
                            SoLuong = 18,
                            TenSp = "Bánh su kem nhỏ"
                        },
                        new
                        {
                            MaSp = "9",
                            DonGia = 18000m,
                            MaNcc = "NCC4",
                            SoLuong = 40,
                            TenSp = "Bánh macaron"
                        },
                        new
                        {
                            MaSp = "10",
                            DonGia = 20000m,
                            MaNcc = "NCC4",
                            SoLuong = 22,
                            TenSp = "Bánh su kem matcha"
                        },
                        new
                        {
                            MaSp = "11",
                            DonGia = 32000m,
                            MaNcc = "NCC4",
                            SoLuong = 14,
                            TenSp = "Bánh mousse xoài"
                        },
                        new
                        {
                            MaSp = "12",
                            DonGia = 25000m,
                            MaNcc = "NCC5",
                            SoLuong = 30,
                            TenSp = "Bánh kem socola"
                        },
                        new
                        {
                            MaSp = "13",
                            DonGia = 30000m,
                            MaNcc = "NCC5",
                            SoLuong = 16,
                            TenSp = "Bánh tiramisu"
                        },
                        new
                        {
                            MaSp = "14",
                            DonGia = 28000m,
                            MaNcc = "NCC5",
                            SoLuong = 20,
                            TenSp = "Bánh mochi"
                        },
                        new
                        {
                            MaSp = "15",
                            DonGia = 35000m,
                            MaNcc = "NCC5",
                            SoLuong = 9,
                            TenSp = "Bánh mousse"
                        },
                        new
                        {
                            MaSp = "16",
                            DonGia = 22000m,
                            MaNcc = "NCC5",
                            SoLuong = 19,
                            TenSp = "Bánh su kem"
                        },
                        new
                        {
                            MaSp = "17",
                            DonGia = 18000m,
                            MaNcc = "NCC5",
                            SoLuong = 50,
                            TenSp = "Bánh flan"
                        },
                        new
                        {
                            MaSp = "18",
                            DonGia = 20000m,
                            MaNcc = "NCC5",
                            SoLuong = 35,
                            TenSp = "Bánh quy bơ"
                        },
                        new
                        {
                            MaSp = "19",
                            DonGia = 32000m,
                            MaNcc = "NCC5",
                            SoLuong = 22,
                            TenSp = "Bánh cupcake"
                        });
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Project2_TaiTungHung.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHoa__MaHD__4E88ABD4");

                    b.HasOne("Project2_TaiTungHung.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHoa__MaSP__4F7CD00D");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.HoaDon", b =>
                {
                    b.HasOne("Project2_TaiTungHung.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__HoaDon__MaKH__403A8C7D");

                    b.HasOne("Project2_TaiTungHung.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__HoaDon__MaNV__412EB0B6");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.SanPham", b =>
                {
                    b.HasOne("Project2_TaiTungHung.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__SanPham__MaNCC__3D5E1FD2");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Project2_TaiTungHung.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
